### ISSUE TITLE
Please bump or relax pyyaml version dependency

### ISSUE THREAD

**Issue by traut** [usePF/dendrol#5]
pyyaml 3.13 solves major issue for macos - https://github.com/yaml/pyyaml/issues/152

Please bump pyyaml dependency to 3.13 or relax it, so that 3.13 can be used with latest version of dendrol

**Comment by theY4Kman** [comment]
Req changed to `PyYAML>=3.12,<4` in dendrol 0.0.5, and [published to PyPI](https://pypi.org/project/dendrol/0.0.5/).

Thanks for the heads-up, and apologies for the delay
