### ISSUE TITLE
python 3.5 SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ybdesire** [usePF/dendrol#6]
any help for below at python 3.5 ? 

```
 [xxxx dendrol-0.0.3]$ sudo python setup.py install
  File "setup.py", line 13
    def get_readme() -> str:
                     ^
SyntaxError: invalid syntax
```

**Comment by theY4Kman** [comment]
I love me some `type: hints` and `awesome(**spread, **operators)` — not to mention the upcoming EOL — so I won't support py2.

However, I spent a few minutes and pasteurized the py3 version, so you can use dendrol on python 2: https://pypi.org/project/dendrol/0.0.5.dev2/

```bash
pip install dendrol==0.0.5.dev2
```

Holler if you have any trouble. I don't love Python 2, but I do love helpin :)

**Comment by ybdesire** [comment]
Thanks @theY4Kman . I have corrected the title. Would you check the real issue for python3.5 ?

**Comment by theY4Kman** [comment]
Whoops, my misunderstanding! Here's a one-off for python3.5: https://pypi.org/project/dendrol/0.0.5.dev35/
```bash
pip install dendrol==0.0.5.dev35
```

**Comment by ybdesire** [comment]
Got that. Thanks a lot for the py3.5 support. @theY4Kman
