### ISSUE TITLE
Would you help check the expression tree parsing?

### ISSUE THREAD

**Issue by ybdesire** [usePF/dendrol#7]
Hi @theY4Kman ,

Have a good day.

I have a trouble to parse the dendrol outputted python structures to AND-only logic. More details here (https://stackoverflow.com/questions/56849478/how-to-pprse-one-stix-pattern-to-generate-mulit-patterns-for-or-logic). Would you give me some help ?

**Comment by ybdesire** [comment]
I closed this ticket since this is not dendrol issue.  dendrol is great parsing tool which helps me a lot.
Any one has any idea about this issue is highly welcomed.  :)

**Comment by theY4Kman** [comment]
I just saw this. Interesting usage; I wonder what you're up to ;)

I posted an answer on the StackOverflow question, for internet points: https://stackoverflow.com/a/56910033/148585
